### ISSUE TITLE
declare(strict_types = 1) problem

### ISSUE THREAD

**Issue by Triplkrypl** [contributte/thepay-api#7]
I found error in version 4.0.0 caused by strict_types.

Method Tp\Helper\Merchant::buildQuery throw error becouse rawurlencode expects string, integer is given in library.
Integer value comes from method: Tp\Payment::getArgs where into mixed array are puted merchantId and accountId from Tp\MerchantConfig where this values are integers.

**Comment by trejjam** [comment]
Hi, thank you for your report. Can you try it with [v4.0.1](https://github.com/contributte/thepay-api/releases/tag/v4.0.1)?

**Comment by Triplkrypl** [comment]
hi, i tested it and it is work ;-)

**Comment by trejjam** [comment]
Thank you for your cooperation 👍
